version: '2'

services:
  mysql:
    build: ./mysql
    image: nddv95/mysql-db
    container_name: mysql-db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
  kafka:
    build: ./kafka
    image: nddv95/kafka
    container_name: kafka
    volumes:
      - kafka-data:/tmp/data
      - zookeeper-data:/tmp/zookeeper
    ports:
      - 9092:9092
networks:
  esnet:
volumes:
  mysql-data:
  es-data:
  kafka-data:
  zookeeper-data: